baseURL: https://sirnino.github.io
languageCode: it-it
title: Sirnino
theme: toha

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Website and personal blog of Nino Sirchia.

  # background image of the landing page
  background: "assets/images/background.jfif"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /assets/images/logo.png
    inverted: /assets/images/logo.png
    favicon: /assets/images/logo.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/sirnino/sirnino.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  #customMenus:
  #- name: Notes
  #  url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Nino Sirchia"
    nickname: "sirnino"
    image: "/assets/images/default-avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "asirchia@gmail.com"
    # a summary of what you do
    summary:
    - Software Engineer
    - Solution Architect
    - Java developer
