---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  new_doc_ext: ".html"
upload_dir: static/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.68.3
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
